language: nix

script:
  - nix-build -A byte-compile --no-out-link --quiet
  - nix-build -A checkdoc --no-out-link --quiet
  - nix-shell -A package-lint --pure --quiet

cache:
  directories:
    - /nix/store
    - /dev/shm/package-lint