# -*- mode: org; mode: org-make-toc; -*-
* nix-env-install
[[https://melpa.org/#/nix-env-install][file:https://melpa.org/packages/nix-env-install-badge.svg]]

[[https://github.com/akirak/nix-env-install/workflows/CI/badge.svg]]

This package lets you install various (currently only npm) packages using the Nix package manager.
** Table of contents
:PROPERTIES:
:TOC: siblings
:END:
    -  [[#installation][Installation]]
    -  [[#usage][Usage]]
      -  [[#npm-packages][NPM packages]]
      -  [[#uninstalling-packages][Uninstalling packages]]
    -  [[#license][License]]

** Installation
This package is not available on MELPA yet, so please install it using Quelpa, straight.el, or any package manager you prefer.
** Usage
*** NPM packages
Use =nix-env-install-npm= to install npm packages.

It uses [[https://github.com/svanderburg/node2nix][node2nix]], as described in [[https://jingsi.space/post/2019/09/23/nix-install-npm-packages/][this blog post]].
*** Uninstalling packages
You can use =nix-env-install-uninstall= to remove packages installed using =nix-env=.
** License
GPL v3
** COMMENT Meta :noexport:
:PROPERTIES:
:TOC:      ignore
:END:
# The COMMENT keyword prevents GitHub's renderer from showing this entry.
